---
- name: Creates directory
  file:
    path: ~/backend_ec2
    state: directory
- name: "Update apt packages."
  become: true
  apt:
    update_cache: yes
- name: "Add Install nodejs "
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
- name: "Install node 14"
  become: true
  apt:
    name: ["nodejs"]
    update_cache: yes
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Copy folder to host
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend_ec2 
- name: extract backend_ec2 files
  become: true
  shell: |
    cd /home/ubuntu/backend_ec2
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz
- name: start backend
  shell: |
    cd ~/backend_ec2/dist
    pm2 stop default
    pm2 start npm -- start
    pm2 ls
- name: Sleep 10s to wait server before smoke-test
  ansible.builtin.pause:
    seconds: 10